language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-backbone-marionette' ]; then cd .. && eval "mv $currentfolder generator-backbone-marionette" && cd generator-backbone-marionette; fi

